site_name: OpenShift Infrastructure Provider Onboarding Guide
repo_url: https://github.com/openshift/infrastructure-provider-onboarding-guide
edit_uri: edit/main/docs/
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
markdown_extensions:
  - pymdownx.snippets:
      check_paths: true
  - admonition

nav:
  - Welcome: index.md
  - Full integration:
    - 'overview.md'
    - Preparation: 'preparation/index.md'
    - 'Information Gathering': 'information-gathering/index.md'
    - 'OpenShift Enhancement': 'openshift-enhancement/index.md'
    - 'RHCOS': 'rhcos/index.md'
    - 'Installer': 'installer/index.md'
    - 'Cloud Controller Manager': 'cloud-controller-manager/index.md'
    - 'Container Storage Interface Driver': 'container-storage-interface-driver/index.md'
    - 'Machine API Controllers': 'machine-api-controllers/index.md'
    - 'Network Ingress and DNS': 'network-ingress-dns/index.md'
    - 'Infrastructure Metadata Service': 'infrastructure-metadata-service/index.md'
    - 'Continuous Integration': 'continuous-integration-and-testing/index.md'
    - 'Component Infrastructure': 'component-infrastructure/index.md'
    - 'Documentation': 'documentation/index.md'
    - 'Red Hat Relationship': 'red-hat-relationship/index.md'
    - 'Release': 'release/index.md'
  - Validation Tests:
    - validation/index.md
    # - validation/ccsp-overview.md
    # Bug: nested pages is not working properly in mkdocs/readthedocs theme:
    # https://github.com/mkdocs/mkdocs/issues/3111#issuecomment-1634265456
    # - Validation Guides:
    - "Validation Guide: OpenShift Standard Installation | Platform None HighAvailability Topology": validation/guides/validate-standard-platform-none-ha.md
    - "Validation Guide: OpenShift Upgrade Installation | Platform None HighAvailability Topology": validation/guides/validate-upgrade-platform-none-ha.md
    - "Validation Guide: OpenShift Disconnected Installation | Platform None HighAvailability Topology": validation/guides/validate-disconnected-platform-none-ha.md
    - validation/ccsp-submit.md